#!/bin/sh
set -e

# Create save path
case "${MWN_SAVE_PATH:=_tmp}" in
/*) NOTES_PATH="$MWN_SAVE_PATH" ;;
*) NOTES_PATH="/var/www/html/$MWN_SAVE_PATH" ;;
esac
mkdir -p "$NOTES_PATH"

# --- COPY COMMANDS START ---
# Copy the protection .htaccess for the notes folder
cp "/var/www/html/notes.htaccess" "$NOTES_PATH/.htaccess"

# Copy the .htpasswd file to the notes folder (NEW LINE)
cp "/var/www/html/.htpasswd" "$NOTES_PATH/.htpasswd"
# ---------------------------

chown -R www-data:www-data "$NOTES_PATH"

# Run default entrypoint
exec docker-php-entrypoint "$@"
